name: ess
description: emplyee management systems for premier groups

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 12.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.6
  freezed_annotation: ^2.2.0
  fluttertoast:
  stacked: ^2.3.15+1
  autocomplete_textfield: ^2.0.0
  flutter_typeahead:
  stacked_services: ^0.9.5
  package_info: ^2.0.2
  dio: ^4.0.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_lints: ^2.0.0
  get: ^4.6.5
  shared_preferences: ^2.0.8
  flutter_slidable: ^2.0.0
  fl_chart: ^0.55.2
  syncfusion_flutter_charts: ^20.4.42
  pie_chart: ^5.3.2
  image_picker: ^0.8.6
  hexcolor: ^3.0.1
  google_fonts: ^3.0.1
  cherry_toast: ^1.0.8
  slide_digital_clock: ^1.0.3
  horizontal_data_table: ^4.1.4
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.3
  firebase_core: ^2.4.1
  file_picker:
  firebase_messaging:
  flutter_local_notifications:
  permission_handler:
  in_app_update: ^4.0.1
  lottie: ^2.2.0
  flutter_multi_formatter: ^2.10.2
  webview_flutter: ^2.0.0
  flutter_spinkit:
  http:
  provider:


dev_dependencies:
  build_runner: ^2.3.3
  stacked_generator: ^0.8.3
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.11.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color: "#ffffff"
  adaptive_icon_background: "#ffffff"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/